version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=roberth.rodriguez@laravelthewebartisan.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    volumes_from:
      - nginx-proxy:rw

  nginx-proxyed:
    image: nginx
    container_name: nginx-proxyed
    expose:
      - 80
    volumes:
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    environment:
      - VIRTUAL_HOST=latam-jobs.com,www.latam-jobs.com
      - LETSENCRYPT_HOST=latam-jobs.com,www.latam-jobs.com

  botpress:
    image: botpress/server
    container_name: botpress
    expose:
      - 3000
    volumes:
      - botpress_data:/botpress/data

volumes:
  botpress_data:
  certs:
  html:
  vhostd:
  acme:
