version: '3'

services:
  botpress:
    image: botpress/server:latest
    container_name: botpress
    working_dir: /var/www
    command: /botpress/bp
    expose:
      - 3000
    volumes:
      - ./botpress/data:/botpress/data
    ports:
      - "3000:3000"
    networks:
      - botpress-network

  nginx:
    image: nginx:latest
    build:
      context: ./
      dockerfile: docker-compose/nginx.dockerfile
    container_name: nginx
    working_dir: /var/www
    restart: unless-stopped
    expose:
      - 443
    ports:
      - "80:80"
      - "443:443"
    volumes:
#      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
#      - ./docker-compose/ssl/self.crt:/var/www/ssl/self.crt
#      - ./docker-compose/ssl/self.key:/var/www/ssl/self.key
    depends_on:
      - botpress
    networks:
      - botpress-network

networks:
  botpress-network:
    driver: bridge