version: '3'

services:
  botpress:
    image: botpress/server:latest
    container_name: botpress
    command: /botpress/bp
    expose:
      - 3000
    volumes:
      - ./botpress/data:/botpress/data
    ports:
      - "3000:3000"
    networks:
      - botpress-network

  nginx:
    image: nginx:1.19.4
    container_name: nginx
    restart: unless-stopped
    expose:
      - 80
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    depends_on:
      - botpress
    networks:
      - botpress-network

networks:
  botpress-network:
    driver: bridge