version: '3'

services:
  botpress:
    image: botpress/server:latest
    container_name: botpress
    command: /botpress/bp
    expose:
      - 3000
    volumes:
      - ./botpress/data:/botpress/data
    ports:
      - "3000:3000"
    networks:
      - botpress-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    expose:
      - 80
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - botpress
    networks:
      - botpress-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www --email roberth.rodriguez@laravelthewebartisan.com --agree-tos --no-eff-email --staging -d botpress.laravelthewebartisan.com;

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/roberth/botpress_project/views/
      o: bind

networks:
  botpress-network:
    driver: bridge
