version: '3'

services:
  botpress:
    image: botpress/server:latest
    container_name: botpress
    working_dir: /var/www
    command: /botpress/bp
    expose:
      - 3000
    volumes:
      - ./botpress/data:/botpress/data
    ports:
      - "3000:3000"
    networks:
      - botpress-network

  nginx:
    image: nginx:latest
    build:
      context: ./
      dockerfile: docker-compose/nginx/Dockerfile
    container_name: nginx
    working_dir: /var/www
    restart: unless-stopped
    expose:
      - 443
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker-compose/nginx:/etc/nginx/conf.d
    depends_on:
      - botpress
    networks:
      - botpress-network
  certbot:
    image: certbot/certbot

networks:
  botpress-network:
    driver: bridge
    volumes:
    - ./docker-compose/certbot/conf:/etc/letsencrypt
    - ./docker-compose/certbot/www:/var/www/certbot