version: '3'

services:
  nginx-botpress:
    image: nginx:1.19.4
    container_name: nginx-botpress
    restart: always
    expose:
      - 80
    volumes:
      - ./docker-compose/nginx:/etc/nginx/conf.d
    environment:
      - VIRTUAL_HOST=botpress.laravelthewebartisan.com
      - LETSENCRYPT_HOST=botpress.laravelthewebartisan.com
      - LETSENCRYPT_EMAIL=roberth.rodriguez@laravelthewebartisan.com
    networks:
      - botpress-network

  botpress:
    image: botpress/server:v12.23.2
    container_name: botpress
    working_dir: /var/www
    command: /botpress/bp
    expose:
      - 3000
    volumes:
      - ./botpress/data:/botpress/data
    ports:
      - "3000:3000"
    networks:
      - botpress-network

networks:
  botpress-network:
    driver: bridge
  default:
    external:
      name: proxynet