version: '3'

services:
  botpress:
    image: botpress/server:latest
    container_name: botpress
    command: /botpress/bp
    expose:
      - 3000
    volumes:
      - ./botpress/data:/botpress/data
    ports:
      - "3000:3000"
    networks:
      - botpress-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - botpress-network

networks:
  botpress-network:
    driver: bridge