name: CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set credentials
      run: |
        git config --local user.email "rrodriguezj@uni.pe"
        git config --local user.name "Roberth Rodriguez"