name: CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: CD deploy
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Commit built assets
      run: |
        git config --local user.email "rrodriguezj@uni.pe"
        git config --local user.name "Roberth Rodriguez"
        git checkout -B deploy
        git push -f origin deploy