name: CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set credentials
      run: |
        docker-compose down --remove-orphans
        docker-compose up -d